services:
  express:
    restart: always
    build:
      context: ./express
      dockerfile: Dockerfile.prod
    env_file:
      - ./.env
    ports:
      - "80:3000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - ./mongo:/data/db
      - ./db:/backup

  redis:
    image: redis
