#!/bin/zsh

backend() {
  local op=$1
  cd backend
  case $op in
    "up")
      if [[ $env == "prod" ]]; then
        docker compose -f docker-compose.prod.yml up -d
      else
        docker compose up -d
      fi
      ;;
    "build")
      docker compose up --build --force-recreate --no-deps -d
      ;;
    "re")
      docker restart backend-express-1
      ;;
    "down")
      docker compose down
      ;;
    "log")
      docker logs backend-express-1 --tail 100 -f
      ;;
    "sh")
      docker exec -it backend-express-1 sh
      ;;
    "backup")
        docker exec -i backend-mongo-1 mongodump -d merndb -o /backup
        ;;
    "restore")
        docker exec -i backend-mongo-1 mongorestore -d merndb --dir /backup/merndb --drop
        ;;
  esac
  cd ..
}

frontend() {
  local op=$1
  cd frontend
  case $op in
    "dev")
      npm run start
      ;;
    "build")
      npm run build
      ;;
    "test")
      npm run test
      ;;
  esac
  cd ..
}

case $1 in
  "back")
    backend $2
    ;;

  "front")
    frontend $2
    ;;
  *)
    echo "Usage:"
    echo "  ./server back <command>    - Run backend commands (up/build/down/log/sh/re/backup/restore)"
    echo "  ./server front <command>   - Run frontend commands (dev/build/test)"
    ;;
esac
