# Build stage
FROM node:22-alpine AS builder
WORKDIR /build

COPY package*.json ./
RUN npm install

COPY tsconfig.json ./
COPY ./src ./src
RUN npm run build

# Production stage
FROM node:22-alpine
WORKDIR /app

COPY package*.json ./
RUN npm ci --production

COPY --from=builder /build/dist ./dist
COPY spa ./spa
COPY public ./public

CMD ["npm", "start"]
