services:
  express:
    restart: always
    build: ./express
    volumes:
      - ./express/src:/app/src
      - ./express/spa:/app/spa
      - ./express/public:/app/public
      - ./express/eslint.config.js:/app/eslint.config.js
      - ./express/jest.config.json:/app/jest.config.json
      - ./express/vite.config.ts:/app/vite.config.ts
    env_file:
      - .env
    ports:
      - "80:3000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
      - ./db:/backup

  redis:
    image: redis