services:
  express:
    restart: always
    build: ./express
    env_file:
      - .env
    ports:
      - "80:3000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    volumes:
      - ./mongo:/data/db
      - ./db:/backup

  redis:
    image: redis
