services:
  express:
    restart: always
    build: ./express
    volumes:
      - ./express/src:/app/src
      - ./express/spa:/app/spa
      - ./express/public:/app/public
    env_file:
      - .env
    ports:
      - "80:3000"
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo:/data/db
      - ./db:/backup

  redis:
    image: redis