name: Backend CI

on:
  push:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and start services
        run: docker-compose up --build -d

      # - name: Run backend tests (inside container)
      #   run: docker-compose exec -T backend npm test

      - name: Stop containers
        run: docker-compose down