name: deploy to digital ocean

on:
  push:
    branches:
      - build

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js (frontend)
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install frontend dependencies
        run: npm ci
        working-directory: frontend

      - name: Build frontend web app
        run: npm run build --prefix ./frontend 

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_NAME }}
          password: ${{ secrets.DOCKERHUB_PAT }}

      - name: Build and push to Docker Hub
        run: |
          IMG=${{ secrets.DOCKERHUB_NAME }}/my-express:latest
          docker build -t $IMG -f backend/Dockerfile .
          docker push $IMG
        working-directory: backend
